ReportCardManagementApp/ReportCardManagementApp/Controllers/StudentClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReportCardManagementApp.Models;
using ReportCardManagementApp.ViewModels;

namespace ReportCardManagementApp.Controllers
{
    public class StudentClassesController : Controller
    {
        private ReportCardDBEntities db = new ReportCardDBEntities();

        // GET: StudentClasses
        public async Task<ActionResult> Index()
        {
            var studentClasses = db.StudentClasses.Include(s => s.Class).Include(s => s.Student);

            StudentClassesIndexViewModel model = new StudentClassesIndexViewModel();

            var listOfsec = db.Classes.Select(x => new StudentClassesIndexViewModel.StudentEnrollmentClasses()
            {
                ClassID = x.ClassID,
                ClassName = x.ClassName,
                NumberOfEnrollments = x.StudentClasses.Count
            });
            model.Counts = await listOfsec.ToListAsync();
            return View(model);
        }

        public async Task<ActionResult> EnrollmentList(int id)
        {
            Class inclass = await db.Classes.FindAsync(id);

            var listOfEnrolled = db.StudentClasses.Where(x => x.ClassID == inclass.ClassID);

            List<StudentClass> enrolled = await listOfEnrolled.ToListAsync();

            ViewBag.ClassName = inclass.ClassName;

            return View(enrolled);
        }

        // GET: StudentClasses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = await db.StudentClasses.FindAsync(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            return View(studentClass);
        }

        // GET: StudentClasses/Create
        public ActionResult Create()
        {
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode");
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName");
            return View();
        }

        // POST: StudentClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StudentID,ClassID,DateFrom,DateTo")] StudentClass studentClass)
        {
            if (ModelState.IsValid)
            {
                db.StudentClasses.Add(studentClass);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", studentClass.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", studentClass.StudentID);
            return View(studentClass);
        }

        // GET: StudentClasses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = await db.StudentClasses.FindAsync(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", studentClass.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", studentClass.StudentID);
            return View(studentClass);
        }

        // POST: StudentClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StudentID,ClassID,DateFrom,DateTo")] StudentClass studentClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentClass).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", studentClass.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", studentClass.StudentID);
            return View(studentClass);
        }

        // GET: StudentClasses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = await db.StudentClasses.FindAsync(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            return View(studentClass);
        }

        // POST: StudentClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            StudentClass studentClass = await db.StudentClasses.FindAsync(id);
            db.StudentClasses.Remove(studentClass);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/Create.cshtml
@model ReportCardManagementApp.Models.StudentClass

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Student@*@Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassID, "ClassID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/Delete.cshtml
@model ReportCardManagementApp.Models.StudentClass

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/Details.cshtml
@model ReportCardManagementApp.Models.StudentClass

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StudentClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/Edit.cshtml
@model ReportCardManagementApp.Models.StudentClass

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentID)

        @Html.HiddenFor(model => model.ClassID)

        @Html.HiddenFor(model => model.DateFrom)

        <div class="form-group">
            @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/EnrollmentList.cshtml
@model IEnumerable<ReportCardManagementApp.Models.StudentClass>

@{
    ViewBag.Title = "EnrollmentList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.ClassName - Enrollment List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table id="example" class="display dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>
                Student Name
            </th>
        </tr>
    </thead>
    

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("Details", "Students", new { id = item.StudentID })">@item.Student.FirstName @item.Student.LastName</a>
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new {  }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
        }

    </table>

ReportCardManagementApp/ReportCardManagementApp/Views/StudentClasses/Index.cshtml
@model ReportCardManagementApp.ViewModels.StudentClassesIndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Enrollment</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="example" class="display dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>
                Class Name
            </th>
            <th>
                Number Enrolled
            </th>
        </tr>
    </thead>

@foreach (var item in Model.Counts) {
    <tr>
        <td>
            <a href="@Url.Action("EnrollmentList", "StudentClasses", new { id = item.ClassID })"> @Html.DisplayFor(modelItem => item.ClassName) </a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfEnrollments)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>