ReportCardManagementApp/ReportCardManagementApp/Models/Homework.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCardManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int HomeworkID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string HomeWorkContent { get; set; }
        public Nullable<double> Grade { get; set; }
        public string OtherHomeworkDetails { get; set; }
        public int ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}

ReportCardManagementApp/ReportCardManagementApp/Controllers/HomeworkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReportCardManagementApp.Models;
using ReportCardManagementApp.ViewModels;

namespace ReportCardManagementApp.Controllers
{
    public class HomeworkController : Controller
    {
        private ReportCardDBEntities db = new ReportCardDBEntities();

        // GET: Homework
        public ActionResult Index(string filter)
        {
            return View(FilterHomework(filter));
        }

        public List<Homework> FilterHomework(string filter)
        {
            List<Homework> hwList = new List<Homework>();
            var homework = db.Homework.Include(h => h.Class).Include(h => h.Student);
            
            if(!string.IsNullOrEmpty(filter))
            {
                if (filter.Equals("Assigned"))
                {
                    foreach (Homework hw in homework)
                    {
                        if (hw.Grade == 0)
                        {
                            hwList.Add(hw);
                        }
                    }
                    ViewBag.Filter = "Assigned";
                    return hwList;
                }
                else if (filter.Equals("Turned In"))
                {
                    foreach (Homework hw in homework)
                    {
                        if (hw.Grade == 1)
                        {
                            hwList.Add(hw);
                        }
                    }
                    ViewBag.Filter = "Turned In";
                    return hwList;
                }
                else if (filter.Equals("Graded"))
                {
                    foreach (Homework hw in homework)
                    {
                        if (hw.Grade > 1)
                        {
                            hwList.Add(hw);
                        }
                    }
                    ViewBag.Filter = "Graded";
                    return hwList;
                }
                else if(filter.Equals("All"))
                {
                    foreach(Homework hw in homework)
                    {
                        hwList.Add(hw);
                    }
                }
            }

            ViewBag.Filter = "All";
            return homework.ToList();

        }

        public ActionResult ListOfClasses(string filter)
        {
            var classes = db.Classes;
            HomeworkListOfClassesViewModel model = new HomeworkListOfClassesViewModel();
            model.Classes = new List<HomeworkListOfClassesViewModel.ClassWithFilteredHomework>();

            if(string.IsNullOrEmpty(filter))
            {
                filter = "All";
            }

            foreach(Class InClass in classes)
            {
                HomeworkListOfClassesViewModel.ClassWithFilteredHomework cwfh = new HomeworkListOfClassesViewModel.ClassWithFilteredHomework();
                cwfh.InClass = InClass;
                cwfh.Homework = FilterHomework(filter).Where(x => x.ClassID == InClass.ClassID).Count();
                model.Classes.Add(cwfh);
            }

            return View(model);
        }

        public ActionResult ListOfClassHomework(int? id, string filter)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Homework> homeworks = FilterHomework(filter);
            ViewBag.Filter = filter;
            return View(homeworks);
        }

        // GET: Homework/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = await db.Homework.FindAsync(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }

        // GET: Homework/Create
        public ActionResult Create()
        {
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode");
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName");
            return View();
        }

        // POST: Homework/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HomeworkID,StudentID,DateCreated,HomeWorkContent,Grade,OtherHomeworkDetails,ClassID")] Homework homework)
        {
            if (ModelState.IsValid)
            {
                List<StudentClass> enrolledStudents = db.StudentClasses.Where(sc => sc.ClassID == homework.ClassID).ToList();

                foreach(StudentClass sc in enrolledStudents)
                {
                    homework.StudentID = sc.StudentID;
                    db.Homework.Add(homework);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", homework.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", homework.StudentID);
            return View(homework);
        }

        // GET: Homework/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = await db.Homework.FindAsync(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", homework.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", homework.StudentID);
            return View(homework);
        }

        // POST: Homework/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "HomeworkID,StudentID,DateCreated,HomeWorkContent,Grade,OtherHomeworkDetails,ClassID")] Homework homework)
        {
            if (ModelState.IsValid)
            {
                db.Entry(homework).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassCode", homework.ClassID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "FirstName", homework.StudentID);
            return View(homework);
        }

        // GET: Homework/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = await db.Homework.FindAsync(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }

        // POST: Homework/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Homework homework = await db.Homework.FindAsync(id);
            db.Homework.Remove(homework);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/Create.cshtml
@model ReportCardManagementApp.Models.Homework

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.Date.ToString("d"), disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeWorkContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeWorkContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeWorkContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control", @Value = 0, disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherHomeworkDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherHomeworkDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherHomeworkDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassID, "ClassID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/Delete.cshtml
@model ReportCardManagementApp.Models.Homework

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Homework</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeWorkContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeWorkContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherHomeworkDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherHomeworkDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/Details.cshtml
@model ReportCardManagementApp.Models.Homework

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Homework</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeWorkContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeWorkContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherHomeworkDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherHomeworkDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HomeworkID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/Edit.cshtml
@model ReportCardManagementApp.Models.Homework

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HomeworkID)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeWorkContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeWorkContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeWorkContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherHomeworkDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherHomeworkDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherHomeworkDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassID, "ClassID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/Index.cshtml
@model IEnumerable<ReportCardManagementApp.Models.Homework>

@{
    ViewBag.Title = "Index";
}

<h2>Homework (@ViewBag.Filter)</h2>

<p>
    @Html.ActionLink("View All", "Index", "Homework", new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Assigned", "Index", "Homework", new { filter = "Assigned"}, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Turned In", "Index", "Homework", new { filter = "Turned In"}, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Graded", "Index", "Homework", new { filter = "Graded" }, new { @class = "btn btn-primary btn-large" })
</p>


<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table id="example" class="display dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>
                Day Assigned @*@Html.DisplayNameFor(model => model.DateCreated)*@
            </th>
            <th>
                Assignment Name @*@Html.DisplayNameFor(model => model.HomeWorkContent)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                Other Details @*@Html.DisplayNameFor(model => model.OtherHomeworkDetails)*@
            </th>
            <th>
                Class Name @*@Html.DisplayNameFor(model => model.Class.ClassCode)*@
            </th>
            <th>
                Student @*@Html.DisplayNameFor(model => model.Student.FirstName)*@
            </th>
            <th></th>
        </tr>
    </thead>
    

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomeWorkContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OtherHomeworkDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Class.ClassName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.LastName), @Html.DisplayFor(modelItem => item.Student.FirstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HomeworkID }) |
            @Html.ActionLink("Details", "Details", new { id=item.HomeworkID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.HomeworkID })
        </td>
    </tr>
}

</table>

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/ListOfClassHomework.cshtml
@model IEnumerable<ReportCardManagementApp.Models.Homework>

@{
    ViewBag.Title = "ListOfClassHomework";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Class Homework (@ViewBag.Filter)</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeWorkContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherHomeworkDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.ClassCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomeWorkContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OtherHomeworkDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Class.ClassCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.FirstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HomeworkID }) |
            @Html.ActionLink("Details", "Details", new { id=item.HomeworkID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.HomeworkID })
        </td>
    </tr>
}

</table>

ReportCardManagementApp/ReportCardManagementApp/Views/Homework/ListOfClasses.cshtml
@model ReportCardManagementApp.ViewModels.HomeworkListOfClassesViewModel
@{
    ViewBag.Title = "ListOfClasses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Homework - @ViewBag.Filter - List of Classes</h2>

<table id="example" class="display dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>
                Class Name
            </th>
            <th>
                Subject
            </th>
            <th>
                Teacher
            </th>
            <th>
                Assignments
            </th>
        </tr>
    </thead>
    

    @foreach (var item in Model.Classes)
    {
        <tr>
            <td>
                <a href="@Url.Action("ListOfClassHomework", "Homework", new { id = item.InClass.ClassID, filter = "Turned In" })">@Html.DisplayFor(modelItem => item.InClass.ClassName)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InClass.Subject.SubjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InClass.Teacher.FirstName) , @Html.DisplayFor(modelItem => item.InClass.Teacher.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Homework)
            </td>
        </tr>
    }

</table>